MVC_IDENTITY_EXAMPLE(UI)/Models/CarViewModel.cs
using Domain.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_IDENTITY_EXAMPLE_UI_.Models
{
    public class CarViewModel
    {
        public int Id { get; set; }
        public bool IsNew { get; set; }
        [Required]
        public decimal CarPrice { get; set; }
        [Required]
        public int RunRange { get; set; }
        [Required]
        public string CarBrend { get; set; }
        [Required]
        public string ModelName { get; set; }
        public IList<string> ImagePathes { get; set; }
        #region Configuration
        public bool IsHaveCondicioner { get; set; }
        public bool IsHaveSeatsHeating { get; set; }
        public bool IsHaveCruiseControl { get; set; }
        public bool IsHaveGarageSaving { get; set; }
        public bool IsHaveDontHit { get; set; }
        public bool IsHaveFirstOwner { get; set; }
        public bool IsHaveMp3 { get; set; }
        public bool IsHaveSubbufer { get; set; }
        public bool IsHaveAirBags { get; set; }
        public bool IsHaveSleepingCheck { get; set; }
        #endregion
        [Required]
        public string GearBoxType { get; set; }
        public int GearCount { get; set; }
        [Required]
        public string DriverianType { get; set; }
        public int DoorsCount { get; set; }
        [Required]
        public string BodyType { get; set; }

        #region Engine
        public decimal? Volume { get; set; }
        public int CylinderCount { get; set; }
        [Required]
        public string PetrolType { get; set; }
        public int MaxPower { get; set; }
        public int MaxTorque { get; set; }
        public int MaxRpm { get; set; }
        public int MaxPowerRpm { get; set; }
        public int MaxTorqueRpm { get; set; }
        public decimal CityСonsumption { get; set; }
        public decimal AutobanСonsumption { get; set; }
        public decimal MidleСonsumption { get; set; }
        [Required]
        public string BoostType { get; set; }
        #endregion
    }
}

MVC_IDENTITY_EXAMPLE(UI)/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using BLL.Service;
using BLL.Dto;
using MVC_IDENTITY_EXAMPLE_UI_.Models;
using AutoMapper;
using Domain.Model;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;
using System;

namespace MVC_IDENTITY_EXAMPLE_UI_.Controllers
{
    public class CarController : Controller
    {
        private readonly CarService _carService;
        private readonly IMapper _mapper;

        public CarController(CarService carService, IMapper mapper)
        {
            this._carService = carService;
            this._mapper = mapper;
        }
        [HttpGet]
        public async Task<ActionResult> BiggestSearch() => await Task.Run(() => View());

        [HttpPost]
        public async Task<ActionResult> GetCarPartialAsync(FilterViewModel filter)
        {
            var filterDto = _mapper.Map<FilterDto>(filter);
            var cars = await _carService.GetAllCarsAsync(filterDto);
            return PartialView("GetCarPartial", cars);
        }
        [HttpGet]
        public async Task<ActionResult> GetCarAsync(int id)
        {
            var car = _carService.GetCarAsync(id);
            return await Task.Run(() => View(car));
        }
        [HttpGet]
        public async Task<ActionResult> Index() =>  await Task.Run(() => View());

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Create() => await Task.Run(() => View());

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<ActionResult> Create(CarViewModel carVM)
        {
            if (ModelState.IsValid)
            {
                var car = _mapper.Map<Car>(carVM);
                var user = new User() { UserName = User.Identity.Name};
                await _carService.AddCarAsync(car, user);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

MVC_IDENTITY_EXAMPLE(UI)/Views/Car/Cars.cshtml
@model List<Domain.Model.Car>

@foreach (var car in Model)
{
    <div class="col-md-3">
        <img src="asd" @*@car.ImagePathes.First()*@ />
        <h2>@car.CarBrend @car.ModelName</h2>
        <h3>Price: @car.CarPrice $</h3>
        <h4>Range: @car.RunRange</h4>
        <p>Fuel: @car.Engine.PetrolType</p>
        <p>Emgine: @car.Engine.Volume</p>
        <p>Gear Box: @car.GearBoxType</p>
        <p>Driverian: @car.DriverianType</p>
    </div>
}

MVC_IDENTITY_EXAMPLE(UI)/Views/Car/Create.cshtml
@model CarViewModel

@{
    ViewData["Title"] = "Create";
}
<style>
    *, *:before, *:after {
        -moz-box-sizing: border-box;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
    }

    html {
        /*Image only BG fallback*/
        /*background = gradient + image pattern combo*/
    }

    body {
        font-family: 'Nunito', sans-serif;
        color: #384047;
    }

    form {
        max-width: 900px;
        margin: 4% auto;
        padding: 10px 20px;
        background: #D3C8F5;
        border-radius: 8px;
    }

    h1 {
        margin: 0 0 5% 0;
        text-align: center;
    }

    h3 {
        margin: 2% 0 4% 0;
        text-align: center;
    }

    h4 {
        margin: 4% 0 2% 0;
        text-align: left;
    }

    input[type="text"],
    input[type="password"],
    input[type="date"],
    input[type="datetime"],
    input[type="email"],
    input[type="number"],
    input[type="search"],
    input[type="tel"],
    input[type="time"],
    input[type="url"],
    textarea,
    select {
        font-size: 16px !important;
        height: auto !important;
        color: none !important;
        box-shadow: 0 0 1px 1px rgba(22, 12, 50, 0.5) inset !important;
        background: none !important;
        display: block !important;
        margin: 20px auto !important;
        text-align: center !important;
        border: 2px solid #241455 !important;
        padding: 14px 10px !important;
        width: 200px !important;
        outline: none !important;
        color: #331C78 !important;
        border-radius: 24px !important;
        transition: 0.25s !important;
    }

        input[type = "text"]:focus,
        input[type = "password"]:focus
        input[type="date"]:focus,
        input[type="datetime"]:focus,
        input[type="email"]:focus,
        input[type="number"]:focus,
        input[type="search"]:focus,
        input[type="tel"]:focus,
        input[type="time"]:focus,
        input[type="url"]:focus {
            width: 280px !important;
            border-color: #239B7D !important;
        }

    input[type="radio"],
    input[type="checkbox"] {
        margin-top: 3%;
        margin-left: 2.5%;
        margin-right: 2.5%;
        transform: scale(2);
        opacity: 0.9;
        cursor: pointer;
    }
        /*        input[type="checkbox"]:checked {
            background: radial-gradient(rgba(36, 20, 85, 1), rgba(22, 12, 50, 1));
        }*/
        input[type="radio"]:checked,
        input[type="checkbox"]:checked {
            transform: scale(2.5);
        }

    input[type = "submit"] {
        border: 0 !important;
        background: none !important;
        display: block !important;
        margin: 20px auto !important;
        text-align: center !important;
        border: 2px solid #239B7D !important;
        padding: 14px 40px !important;
        outline: none !important;
        color: #331C78 !important;
        border-radius: 24px !important;
        transition: 0.25s !important;
        cursor: pointer !important;
        width: 50% !important;
    }

        input[type = "submit"]:hover {
            background: #239B7D !important;
            color: #331C78 !important;
            width: 280px !important;
        }



    select {
        padding: 6px;
        height: 32px;
        border-radius: 2px;
    }

    button {
        padding: 19px 39px 18px 39px;
        color: #FFF;
        background-color: #239B7D;
        font-size: 18px;
        text-align: center;
        font-style: normal;
        border-radius: 5px;
        width: 100%;
        border: 1px solid #331C78;
        border-width: 1px 1px 3px;
        box-shadow: 0 -1px 0 rgba(255,255,255,0.1) inset;
        margin-bottom: 5%;
    }

    fieldset {
        margin-bottom: 3%;
        border: none;
        width: 30%
    }

    legend {
        font-size: 1.4em;
        margin-bottom: 4%;
    }

    label {
        display: block;
        margin-bottom: 2%;
    }

        label.light {
            font-weight: 300;
            display: inline;
        }

    .number {
        background-color: #239B7D;
        color: #fff;
        height: 30px;
        width: 30px;
        display: inline-block;
        font-size: 0.8em;
        margin-right: 4px;
        line-height: 30px;
        text-align: center;
        text-shadow: 0 1px 0 rgba(255,255,255,0.2);
        border-radius: 100%;
    }

    label {
        font-size: 20px;
        margin-left: 4%;
        font-weight: 200;
    }
</style>

@using (Html.BeginForm("Create", "Car", FormMethod.Post))
{
    <h1> Create Car</h1>
    <div class="row" style="display:flex; text-align:center">
        <div style="width:33%;display:flex; justify-content:space-around">
            <legend><span class="number">1</span>Basic info</legend>
        </div>
        <div style="width:66%;display:flex; text-align:center">
            <legend><span class="number">2</span>Configuration</legend>
        </div>
    </div>
    <div class="row" style="display:flex; justify-content:space-around">

        <fieldset>


            <input type="number" name="CarPrice" placeholder="Car Price" />
            <input type="number" name="RunRange" placeholder="Run Range" />
            <input type="number" name="ProductionYear" placeholder="Production year" />

            <input type="checkbox" value="true" name="isNew"><label class="light">New Car</label><br>


            <h4>Brand:</h4>
            <select id="brend" name="CarBrend">

                <option value="Audi">Audi</option>
                <option value="Nissan">Nissan</option>
                <option value="Dodge">Dodge</option>
                <option value="Bentley">Bentley</option>
            </select>
            <h4>Model:</h4>
            <select id="model" name="ModelName">
                <option value="RS3">RS3</option>
                <option value="GT-R">GT-R</option>
                <option value="Durando">Durando</option>
                <option value="Flying Spur">Flying Spur</option>
            </select>

        </fieldset>

        <fieldset>
            <h3>Transmistion</h3>
            <select id="GearBox" name="GearBoxType">
                <option value="1">Gb 1</option>
                <option value="2">Gb 2</option>
                <option value="3">Gb 3</option>
            </select>
            <input type="number" name="GearCount" placeholder="Gear count" />
            <select id="Driverian" name="DriverianType">
                <option value="1">Dv 1</option>
                <option value="2">Dv 2</option>
                <option value="3">Dv 3</option>
            </select>

            <h3>Body</h3>
            <select id="GearBox" name="BodyType">
                <option value="Body1">Body 1</option>
                <option value="Body2">Body 2</option>
                <option value="Body3">Body 3</option>
            </select>

            <input type="number" name="DoorsCount" placeholder="Doors count" />

            <h3>Engine</h3>


            <input type="number" name="Volume" placeholder="Engine volume(in mililiters)" />
            <input type="number" name="CylinderCount" placeholder="Cylinder count" />
            <select id="Petrol" name="PetrolType">
                <option value="Petrol">Petrol</option>
                <option value="Gas/Petrol">Gas/Petrol</option>
                <option value="Gas">Gas</option>
                <option value="Diesel">Diesel</option>
                <option value="Hibrid">Hibrid</option>
                <option value="Electric">Electric</option>
            </select>
            <input type="number" name="MaxPower" placeholder="maxPower" />
            <input type="number" name="MaxTorque" placeholder="MaxTorque" />
            <input type="number" name="MaxRpm" placeholder="MaxRpm" />
            <input type="number" name="MaxPowerRpm" placeholder="MaxPowerRpm" />
            <input type="number" name="MaxTorqueRpm" placeholder="MaxTorqueRpm" />
            <input type="number" name="CityСonsumption" placeholder="City Сonsumption" />
            <input type="number" name="AutobanСonsumption" placeholder="Autoban Сonsumption" />
            <input type="number" name="MidleСonsumption" placeholder="Midle Сonsumption" />
            <select id="Boost" name="BoostType">
                <option value="N/A">N/A</option>
                <option value="Supercharger">Supercharger</option>
                <option value="Single Turbo">Single Turbo</option>
                <option value="Twin turbo">Twin turbo</option>
                <option value="Bi turbo">Bi turbo</option>
            </select>

        </fieldset>

        <fieldset>
            <h3>Comfort</h3>
            <input type="checkbox" id="ComfortList" value="true" name="IsHaveCondicioner"><label class="light" for="development">Conditioner</label><br>
            <input type="checkbox" id="ComfortList" value="true" name="IsHaveSeatsHeating"><label class="light" for="development">Seats heating</label><br>
            <input type="checkbox" id="ComfortList" value="true" name="IsHaveCruiseControl"><label class="light" for="development">Cruise control</label><br>
            <h3>State</h3>
            <input type="checkbox" id="StateList" value="true" name="IsHaveGarageSaving"><label class="light" for="design">Garage saving</label><br>
            <input type="checkbox" id="StateList" value="true" name="IsHaveDontHit"><label class="light" for="design">Dont hit</label><br>
            <input type="checkbox" id="StateList" value="true" name="IsHaveFirstOwner"><label class="light" for="design">First owner</label><br>
            <h3>Mupti media</h3>
            <input type="checkbox" id="MultiMediaList" value="true" name="IsHaveMp3"><label class="light" for="business">MP3</label><br>
            <input type="checkbox" id="MultiMediaList" value="true" name="IsHaveSubbufer"><label class="light" for="business">Subbuffer</label><br>
            <h3>Save</h3>
            <input type="checkbox" id="SaveList" value="true" name="IsHaveAirBags"><label class="light" for="design">Air bags</label><br>
            <input type="checkbox" id="SaveList" value="true" name="IsHaveSleepingCheck"><label class="light" for="design">Sleeping check</label><br>
        </fieldset>
    </div>
    <input type="submit" value="+Add">
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVC_IDENTITY_EXAMPLE(UI)/Views/Car/GetCar.cshtml
@model Domain.Model.Car

MVC_IDENTITY_EXAMPLE(UI)/Views/Car/GetCarPartial.cshtml
@model List<Domain.Model.Car>


<style>




    .outer {
        margin: 20px auto;
        position: relative;
        background-color: rgba(30,30,30,0.2);
        height: 250px;
        width: 450px;
        overflow: hidden;
        display: flex;
        align-items: center;
        border-radius: 20px;
    }

    img {
        position: absolute;
        top: 0px;
        right: -20px;
        z-index: 0;
        animation-delay: 0.5s;
    }

    .content {
        animation-delay: 0.3s;
        position: absolute;
        left: 20px;
        z-index: 3
    }

    h1 {
        color: #111;
        margin-top: 5%
    }

    p {
        width: 280px;
        font-size: 13px;
        line-height: 1.4;
        color: rgba(22, 12, 50, 0.5);
        margin: 20px 0;
    }

    .bg {
        display: inline-block;
        color: #fff;
        background: #239B7D;
        padding: 5px 10px;
        border-radius: 50px;
        font-size: .7em;
    }

    .button {
        width: fit-content;
        height: fit-content;
        margin-top: 10px;
        margin-left: 50px;
    }

        .button a {
            display: inline-block;
            overflow: hidden;
            position: relative;
            font-size: 11px;
            color: #331C78;
            text-decoration: none;
            padding: 10px 15px;
            border: 1px solid rgba(22, 12, 50, 0.5);
            font-weight: bold;
        }

            .button a:after {
                content: "";
                position: absolute;
                top: 0;
                right: -10px;
                width: 0%;
                background: #239B7D;
                height: 100%;
                z-index: -1;
                transition: width 0.3s ease-in-out;
                transform: skew(-25deg);
                transform-origin: right;
            }

            .button a:hover:after {
                width: 150%;
                left: -10px;
                transform-origin: left;
            }

            .button a:hover {
                color: #fff;
                transition: all 0.5s ease;
            }


            .button a:nth-of-type(1) {
                border-radius: 50px 0 0 50px;
                border-right: none;
            }

            .button a:nth-of-type(2) {
                border-radius: 0px 50px 50px 0;
            }

    .cart-icon {
        padding-right: 8px;
    }
</style>

@foreach (var car in Model)
{
    <!--<div class="col-md-3">
        <img src="asd"--> @*@car.ImagePathes.First()*@
        <!--/>
            <h2>@car.CarBrend @car.ModelName</h2>
            <h3>Price: @car.CarPrice $</h3>
            <h4>Range: @car.RunRange</h4>
            <p>Fuel: @car.Engine.PetrolType</p>
            <p>Emgine: @car.Engine.Volume</p>
            <p>Gear Box: @car.GearBoxType</p>
            <p>Driverian: @car.DriverianType</p>
        </div>-->
        <div class="wrapper">
            <div class="outer">
                <div class="content animated fadeInLeft">
                    <span class="bg animated fadeInDown">EXCLUSIVE</span>
                    <h1>Foking car</h1>
                    <p>Just buy dat car i know you want it.</p>

                    <div class="button">
                        <a href="#">$5.000</a><a class="cart-btn" href="#"><i class="cart-icon ion-bag"></i>ADD TO CART</a>
                    </div>

                </div>
                <img src="http://www.clker.com/cliparts/x/c/q/E/L/j/gray-car-top-view-90-hi.png" height="90%" style="margin-right: 70px; margin-top: 2.5%" class="animated fadeInRight">
            </div>

        </div>
    }

MVC_IDENTITY_EXAMPLE(UI)/Views/Car/Index.cshtml
@model IEnumerable<Domain.Model.Car>

@{
    ViewData["Title"] = "Index";
}



<style>

    body {
        font-family: 'Nunito', sans-serif;
        color: #384047;
    }

    form {
        margin: 4% auto;
        width: 120%;
        margin-left: -10%;
        background: rgba(239, 230, 245,0.9);
        border-radius: 8px;
    }


    input[type="text"],
    input[type="password"],
    input[type="date"],
    input[type="datetime"],
    input[type="email"],
    input[type="number"],
    input[type="search"],
    input[type="tel"],
    input[type="time"],
    input[type="url"],
    textarea,
    select {
        font-size: 16px !important;
        height: 50px !important;
        color: none !important;
        box-shadow: 0 0 1px 1px rgba(22, 12, 50, 0.5) inset !important;
        background: none !important;
        display: block !important;
        margin: 20px auto !important;
        text-align: center !important;
        border: 2px solid #241455 !important;
        padding: 14px 10px !important;
        width: 200px !important;
        outline: none !important;
        color: #331C78 !important;
        border-radius: 24px !important;
        transition: 0.25s !important;
    }

        input[type = "text"]:focus,
        input[type = "password"]:focus
        input[type="date"]:focus,
        input[type="datetime"]:focus,
        input[type="email"]:focus,
        input[type="number"]:focus,
        input[type="search"]:focus,
        input[type="tel"]:focus,
        input[type="time"]:focus,
        input[type="url"]:focus {
            width: 280px !important;
            border-color: #239B7D !important;
        }

    input[type="radio"],
    input[type="checkbox"] {
        margin-top: 3%;
        margin-left: 2.5%;
        margin-right: 2.5%;
        transform: scale(2);
        opacity: 0.9;
        cursor: pointer;
    }
        /*        input[type="checkbox"]:checked {
            background: radial-gradient(rgba(36, 20, 85, 1), rgba(22, 12, 50, 1));
        }*/
        input[type="radio"]:checked,
        input[type="checkbox"]:checked {
            transform: scale(2.5);
        }

    input[type = "button"],
    input[type = "submit"] {
        border: 0 !important;
        background: none !important;
        display: block !important;
        margin: 20px auto !important;
        text-align: center !important;
        border: 2px solid #239B7D !important;
        padding: 14px 40px !important;
        outline: none !important;
        color: #239B7D !important;
        border-radius: 24px !important;
        transition: 0.25s !important;
        cursor: pointer !important;
        width: 90% !important;
    }

        input[type = "button"]:hover,
        input[type = "submit"]:hover {
            background: #239B7D !important;
            color: #331C78 !important;
            width: 200px !important;
        }




    select {
        padding: 6px;
        height: 32px;
        border-radius: 2px;
    }

    button {
        border: 0;
        background: none;
        display: block;
        margin: 20px auto;
        text-align: center;
        border: 2px solid #239B7D;
        padding: 14px 40px;
        outline: none;
        color: #331C78;
        border-radius: 24px;
        transition: 0.25s;
        cursor: pointer;
        width: 240px;
    }

        button:hover {
            background: #239B7D !important;
            color: #331C78 !important;
            width: 280px !important;
        }



    fieldset {
        margin-bottom: 3%;
        border: none;
        width: 30%
    }

    legend {
        font-size: 1.4em;
        margin-bottom: 4%;
    }

    label {
        display: block;
        margin-bottom: 2%;
    }

        label.light {
            font-weight: 300;
            display: inline;
        }

    .number {
        background-color: #239B7D;
        color: #fff;
        height: 30px;
        width: 30px;
        display: inline-block;
        font-size: 0.8em;
        margin-right: 4px;
        line-height: 30px;
        text-align: center;
        text-shadow: 0 1px 0 rgba(255,255,255,0.2);
        border-radius: 100%;
    }

    label {
        font-size: 20px;
        margin-left: 4%;
        margin-left: 4%;
        font-weight: 200;
    }
</style>

<form>
    <div class="row">
        <div class="col" style="width:19%; background-color: rgba(30,30,30,0.1); border-radius: 12px">

            <div class="col">
                <select name="IsNew">
                    <option selected value="null">All statuses</option>
                    <option value="true">New</option>
                    <option value="false">Used</option>
                </select>
            </div>
            <div class="col">
                <select name="BodyType">
                    <option selected value="All">All BodyTypes</option>
                    <option value="Body1">Body1</option>
                    <option value="Body2">Body2</option>
                </select>
                <select name="BrendName">
                    <option selected value="All">All Brands</option>
                    <option value="Brend1">Brend1</option>
                    <option value="Brend2">Brend2</option>
                </select>
                <select name="ModelName">
                    <option selected value="All">All Models</option>
                    <option value="Model1">Model1</option>
                    <option value="Model2">Model2</option>
                </select>
            </div>
            <div class="col">
                <select name="StartYear">
                    <option selected value="All">All StartYears</option>
                    <option value="Year1">Year1</option>
                    <option value="Year2">Year2</option>
                </select>
                <select name="EndYear">
                    <option selected value="All">All EndYears</option>
                    <option value="Year1">Year1</option>
                    <option value="Year2">Year2</option>
                </select>
                <input id="SearchBtnId" type="button" value="Search" />
                <a style="color: #239B7D" style="color: #239B7D" class="nav-link" asp-area="" asp-controller="Car" asp-action="BiggestSearch">Advanced search</a>
            </div>
        </div>
        <div style="width:81%; text-align: center;">
            <h4>Cars</h4>
            <div id="AllCarsDivId" class="row">
                @if(Model != null)
                {
                    Html.RenderPartial("GetCarPartial", Model);
                }
            </div>
        </div>
    </div>
</form>
@section Scripts
    {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
    <script>
            var filter = new Object();
            $('#SearchBtnId').click(function () {

                filter.IsNew = $("select[name='IsNew']").val();
                filter.BodyType = $("select[name='BodyType']").val();
                filter.BrendName = $("select[name='BrendName']").val();
                filter.ModelName = $("select[name='ModelName']").val();
                filter.StartYear = $("select[name='StartYear']").val();
                filter.EndYear = $("select[name='EndYear']").val();

                    $.ajax({
                        type: 'POST',
                        url: '@Url.Content("~/Car/GetCarPartial")',
                        data: filter,
                        //success: function (data) {
                        ///*$("#AllCarsDivId").html(data);*/
                        //    alert(data.responseText);
                        //},
                        error: function (data) {
                            alert(data.responseText);
                        }
                    });
                });
    </script>
}